## 对象存储
#save-config:
#  # 保存模式
#  save-mode: AList
#  # 请求对象地址 (必须)
#  # 可以使用多个地址，程序会自动合并成
#  object-save:
#    - /test/music
##    - /music
#  # 保存地址，必须是对象地址中的值，顺序从0开始
#  # 没有实现随机存储和自动选择最少对象的地址存储，因为存储的上传接口极其不稳定。最后放弃
#  assign-object-save: 0
#  img-save:
#    - /test/img
##    - /img
#  assign-img-save: 0
#  # 请求地址(必须)
#  host: http://localhost:5244
#  # 账户(必须)
#  access-key: admin
#  # 密码(必须)
#  secret-key: h5hbCTzY