server:
  # 配置启动端口号
  port: 8000
  servlet:
    session:
      timeout: 259200000000
      cookie:
        max-age: 259200000000

########## log ##########
logging:
  level:
    org.core: debug
    org.api: debug
    org.oss: debug
    org.web: debug
  pattern:
    # 时间；日志级别；类；方法；行(行不能使用圆括号)
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %C.%M[%line] - %msg%n"

#spring
spring:
  datasource:
    #引用项目中的数据库文件
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whale_music?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart:
      enabled: true
      # 设置 上传文件的大小
      max-file-size: 200MB
      # 设置 整个请求的大小
      max-request-size: 200MB
  jpa:
    #这个参数是在建表的时候，将默认的存储引擎切换为 InnoDB 用的
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #配置在日志中打印出执行的 SQL 语句信息。
    show-sql: true
    open-in-view: true
    hibernate:
      #配置指明在程序启动的时候要删除并且创建实体类对应的表
      ddl-auto: update
      naming:
        #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl


save-config:
  # 保存模式
  save-mode: AList
  # 请求对象地址 (必须)
  object-save: /123
  # 请求地址(必须)
  host: http://43.139.22.243:5244
  # 账户(可选)
  access-key:
  # 密码(可选)
  secret-key:

jwt-config:
  seed-key: ad419e9df4fe41ea1c20bee247a28dce6df8c7cd84c642qw3de5b37bf3e5ec5c
  expire-time: 86400000

file-type:
  suffix:
    - mp3
    - ogg
    - flac