server:
  # 配置启动端口号
  port: 8000
  servlet:
    session:
      timeout: 259200000000
      cookie:
        max-age: 259200000000

########## log ##########
logging:
  level:
    org.core: debug
    org.api: debug
    org.oss: debug
    org.web: debug
  pattern:
    # 控制输出的格式
    #格式化输出：%d:表示日期    %thread:表示线程名     %-5level:级别从左显示5个字符宽度  %msg:日志消息    %n:是换行符
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss:SSS}){blue} %clr(%5p) %clr(%C.%M[%line]){cyan} [%thread] %msg%n"
    # 文件输出的格式
    file: "[file]===%d{yyyy-MM-dd HH:mm:ss:SSS} [%thread] %-5level %logger - %msg%n"

#spring
spring:
  output:
    ansi:
      enabled: always
  datasource:
    #引用项目中的数据库文件
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whale_music?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart:
      enabled: true
      # 设置 上传文件的大小
      max-file-size: 200MB
      # 设置 整个请求的大小
      max-request-size: 200MB
      # 设置上传文件位置
      # location: ./

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #驼峰下划线转换
      table-underline: true

  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 查询大于有效页时，返回有效页最后一页
pagehelper:
  reasonable: true

#save-config:
#  # 保存模式
#  save-mode: AList
#  # 请求对象地址 (必须)
#  # 可以使用多个地址，程序会自动合并成
#  object-save:
#    - /music
#  # 保存地址，必须是对象地址中的值，顺序从0开始
#  # 没有实现随机存储和自动选择最少对象的地址存储，因为存储的上传接口极其不稳定。最后放弃
#  assignObjectSave: 0
#  # 请求地址(必须)
#  host: http://localhost:5244
#  # 账户(必须)
#  access-key: admin
#  # 密码(必须)
#  secret-key: 00000000

jwt-config:
  seed-key: ad419e9df4fe41ea1c20bee247a28dce6df8c7cd84c642qw3de5b37bf3e5ec5c
  expire-time: 86400000

file-type:
  suffix:
    - mp3
    - ogg
    - flac