server:
  # 配置启动端口号
  port: 8000
  servlet:
    session:
      timeout: 259200000000
      cookie:
        max-age: 259200000000

########## log ##########
logging:
  level:
    root: debug
  pattern:
    # 时间；日志级别；类；方法；行(行不能使用圆括号)
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %C.%M[%line] - %msg%n"

#spring
spring:
  datasource:
    #引用项目中的数据库文件
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whale_music?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart:
      enabled: true
      # 设置 上传文件的大小
      max-file-size: 200MB
      # 设置 整个请求的大小
      max-request-size: 200MB
      # 设置上传文件位置
      # location: ./
# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #驼峰下划线转换
      table-underline: true

  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

save-config:
  # 保存模式
  save-mode: AList
  # 请求对象地址 (必须)
  object-save: /123
  # 请求地址(必须)
  host: http://43.139.22.243:5244
  # 账户(可选)
  access-key:
  # 密码(可选)
  secret-key:

jwt-config:
  seed-key: ad419e9df4fe41ea1c20bee247a28dce6df8c7cd84c642qw3de5b37bf3e5ec5c
  expire-time: 86400000

file-type:
  suffix:
    - mp3
    - ogg
    - flac